# Generated by Django 4.1.1 on 2022-09-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=20, unique=True)),
            ],
        ),
    ]
